### ISSUE TITLE
NetHash compilation and execution fail on Linux

### ISSUE THREAD

**Issue by luav** [williamweiwu/williamweiwu.github.io#1]
- Nethash compilation fails because CLOCK is not defined.
- After the CLOCK omission and subsequent successful compilation, the execution (embeddings training) with the default parameters fails with the memory segmentation error because of the excessive allocation of the stack segment:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004046c8 in main (argc=<error reading variable: Cannot access memory at address 0x7ffd34be68fc>, 
    argv=<error reading variable: Cannot access memory at address 0x7ffd34be68f0>) at nethash.cpp:399
399     int main(int argc, char **argv) {
```

**Comment by williamweiwu** [comment]
> * Nethash compilation fails because CLOCK is not defined.
> * After the CLOCK omission and subsequent successful compilation, the execution (embeddings training) with the default parameters fails with the memory segmentation error because of the excessive allocation of the stack segment:
> 
> ```
> Program received signal SIGSEGV, Segmentation fault.
> 0x00000000004046c8 in main (argc=<error reading variable: Cannot access memory at address 0x7ffd34be68fc>, 
>     argv=<error reading variable: Cannot access memory at address 0x7ffd34be68f0>) at nethash.cpp:399
> 399     int main(int argc, char **argv) {
> ```

Please download the latested version and try again.

**Comment by luav** [comment]
The static allocation of a large memory in the stack segment causes the outlined above crash (SIGSEGV on the main entry), the issue is in this line

```c++
int ppt[PPT_SIZE][3];
```
The fix is provided in the pull request, where this and another large structure are allocated dynamically in the heap instead of the stack.

The particular maximal size of the stack segment depends on the host operational system and applied compilation. Anyway, that large arrays should be allocated dynamically to work properly and flexibly with large data.

**Comment by williamweiwu** [comment]
Thank you. i will provide a compatible version. The simple way is to modify the macro define, that is, #define PPT_SIZE, #define MAX_NODE_NUM 1000000000 and #define MAX_FEATURE_NUM 1000000.
